controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

velocity_controllers:
  ros__parameters:
    joints: 
      - rotation_joint_front_left
      - rotation_joint_front_right
      - joint_wheel_rear_left
      - joint_wheel_rear_right
    command_interface: 
      - velocity
    state_interface: 
      - velocity
      - position

forward_position_controller:
  ros__parameters:
    joints:
      - steering_joint_front_left
      - steering_joint_front_right
    interface_name: position

joint_trajectory_position_controller:
  ros__parameters:
    joints:
      - steering_joint_front_left
      - steering_joint_front_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20
    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)

# Steering joint controllers (position)
steering_controller:
  ros__parameters:
    joints:
      - steering_joint_front_left
      - steering_joint_front_right
    command_interface: 
      - position
    state_interface:
      - position
      - velocity

# Wheel joint controllers (velocity)
wheel_controller:
  ros__parameters:
    joints:
      - rotation_joint_front_left
      - rotation_joint_front_right
      - joint_wheel_rear_left
      - joint_wheel_rear_right
    command_interface: 
      - velocity
    state_interface:
      - position
      - velocity
