controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_position_controller:
      type: position_controllers/JointGroupPositionController
    
    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

velocity_controllers:
  ros__parameters:
    joints: 
      - rotation_joint_front_left
      - rotation_joint_front_right
      - joint_wheel_rear_left
      - joint_wheel_rear_right
    command_interface: 
      - velocity
    state_interface: 
      - velocity
      - position

joint_trajectory_position_controller:
  ros__parameters:
    joints:
      - steering_joint_front_left
      - steering_joint_front_right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
